{
  "name": "szpeter-test-4",
  "location": "us-east-1",
  "cloud": "amazon",
  "secretId": "7d1507284a5757cac6b62708a4ef00bfc5d695256489cb704f12b4b9e6255df2",
  "properties": {
    "pke": {
      "nodepools": [
        {
          "name": "master",
          "roles": [
            "master"
          ],
          "provider": "amazon",
          "autoscaling": false,
          "providerConfig": {
            "autoScalingGroup": {
              "name": "master",
              "zones": [
                "us-east-1a"
              ],
              "instanceType": "c5.large",
              "launchConfigurationName": "master",
              "spotPrice": "",
              "size": {
                "desired": 1,
                "min": 1,
                "max": 1
              }
            }
          }
        },
        {
          "name": "pool1",
          "roles": [
            "worker"
          ],
          "provider": "amazon",
          "autoscaling": true,
          "providerConfig": {
            "autoScalingGroup": {
              "name": "pool1",
              "zones": [
                "us-east-1a"
              ],
              "instanceType": "t2.medium",
              "launchConfigurationName": "pool1",
              "spotPrice": "0.05",
              "size": {
                "desired": 1,
                "min": 1,
                "max": 2
              }
            }
          }
        }
      ],
      "kubernetes": {
        "version": "1.14.2",
        "rbac": {
          "enabled": true
        }
      },
      "cri": {
        "runtime": "containerd"
      }
    }
  }
}
